### ISSUE TITLE
TypeError: Cannot read property '0' of undefined at exports.handler (/var/task/index.js:8:43)

### ISSUE THREAD

**Issue by psahanap** [awslabs/cloudwatch-logs-customize-alarms#3]
Getting the below error while executing lambda.
TypeError: Cannot read property '0' of undefined
at exports.handler (/var/task/index.js:8:43)

however we used the same index.js file and updated the mail IDs in SES section. Please suggest, for the error.

**Comment by br45rm** [comment]
On mac you gotta package it from terminal: `% zip -r ../v8.zip *`
