### ISSUE TITLE
CloudWatchLogs filterLogEvents empty events

### ISSUE THREAD

**Issue by uzairfaruki132** [awslabs/cloudwatch-logs-customize-alarms#8]
I am trying to get CloudWatchLogs filterLogEvents by sending parameters. some times it work and sends me the exact logs in that time, but for the different lambda function it returns empty events with next token.

parameters = {

'logGroupName' : metricFilter.logGroupName, 'filterPattern' : metricFilter.filterPattern ? metricFilter.filterPattern : "", 'startTime' : timestamp - offset, 'endTime' : timestamp };

i am retrying by sending parameters with next token but its still getting empty events. Does anyone has idea about it?

{
    "events": [],
    "searchedLogStreams": [],
    "nextToken": "long text"
}

**Comment by ggmr2212** [comment]
I have the same issue? Any resolution?

**Comment by tmpm697** [comment]
I have the same issue, cloudwatch log of lambda shows:
```
INFO	Events are: []

INFO MultipleValidationErrors: There were 3 validation errors:
* MissingRequiredParameter: Missing required key 'Source' in params
* MissingRequiredParameter: Missing required key 'Destination' in params
* MissingRequiredParameter: Missing required key 'Message' in params
at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:40:28)
at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:89:42)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
at /var/task/node_modules/aws-sdk/lib/event_listeners.js:75:9
at finish (/var/task/node_modules/aws-sdk/lib/config.js:308:7)
at /var/task/node_modules/aws-sdk/lib/config.js:324:9
at EnvironmentCredentials.get (/var/task/node_modules/aws-sdk/lib/credentials.js:126:7)
at getAsyncCredentials (/var/task/node_modules/aws-sdk/lib/config.js:318:24)
at Config.getCredentials (/var/task/node_modules/aws-sdk/lib/config.js:338:9) {
code: 'MultipleValidationErrors',
errors: [
MissingRequiredParameter: Missing required key 'Source' in params
at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)
at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:61:14)
at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)
at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)
at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:89:42)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
at /var/task/node_modules/aws-sdk/lib/event_listeners.js:75:9
at finish (/var/task/node_modules/aws-sdk/lib/config.js:308:7)
at /var/task/node_modules/aws-sdk/lib/config.js:324:9 {
code: 'MissingRequiredParameter',
time: 2021-04-09T08:48:32.994Z
},
MissingRequiredParameter: Missing required key 'Destination' in params
at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)
at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:61:14)
at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)
at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)
at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:89:42)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
at /var/task/node_modules/aws-sdk/lib/event_listeners.js:75:9
at finish (/var/task/node_modules/aws-sdk/lib/config.js:308:7)
at /var/task/node_modules/aws-sdk/lib/config.js:324:9 {
code: 'MissingRequiredParameter',
time: 2021-04-09T08:48:32.994Z
```

why is this happen?

**Comment by br45rm** [comment]
I was able to resolve by expanding the time window for cwl.filterLogEvents(). I just changed the offset multiplier to 2000 instead of 1000, like this: `var offset = message.Trigger.Period * message.Trigger.EvaluationPeriods * 2000;`
